apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-master-deploy-priyanshusrivastava01
  namespace: kubernetes-cluster-priyanshusrivastava01
  labels:
    app: java-master-priyanshusrivastava01
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-master-priyanshusrivastava01
  template:
    metadata:
      labels:
        app: java-master-priyanshusrivastava01
    spec:
      containers:
        - name: java-master-priyanshusrivastava01
          image: ps127/i-priyanshusrivastava01-master:latest
          envFrom:
            - configMapRef:
                name: java-master-priyanshusrivastava01
            - secretRef:
                name: java-master-priyanshusrivastava01
                
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: java-master-priyanshusrivastava01
  namespace: kubernetes-cluster-priyanshusrivastava01
  labels:
    app: java-master-priyanshusrivastava01
data:
  API_URL: "https://www.nagarro.com/en"
  BRANCH: "Master"
  DOMAIN: "Java"

---

apiVersion: v1
kind: Secret
metadata:
  name: java-master-priyanshusrivastava01
  namespace: kubernetes-cluster-priyanshusrivastava01
data:
  USER_PWD: "TmFnYXJybw=="
  USER_ID: "TmFnYXJybw=="
type: Opaque

---
apiVersion: v1
kind: Service
metadata:
  name: java-master-priyanshusrivastava01
  namespace: kubernetes-cluster-priyanshusrivastava01
spec:
  type: LoadBalancer
  selector:
    app: java-master-priyanshusrivastava01
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
    nodePort: 30090